on:
  push:

jobs:
  workload-succeeding:
    runs-on: ubuntu-latest
    steps:
    - run: exit 0

  workload-failing:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/failing

    - run: echo "job.status=${{ job.status }}"

    - if: ${{ failure() }}
      run: echo "failure"

    - if: ${{ success() }}
      run: echo "success"

  aggregation:
    runs-on: ubuntu-latest
    needs:
      - workload-succeeding
      - workload-failing
    steps:
      - if: ${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')  }}
        run: echo "success!"

      - if: ${{ contains(needs.*.result, 'failure') }}
        run: echo "failure!"

      - run: echo "failing result ${{ needs.workload-failing.result }}"
      - run: echo "succeeding result ${{ needs.workload-succeeding.result }}"
