name: Test
run-name: "Test (${{ github.ref_name }})"

on:
  workflow_dispatch:
    inputs:
      sha:
        type: string

jobs:
  workload-succeeding:
    runs-on: ubuntu-latest
    steps:
    - run: exit 0

  workload-failing:
    runs-on: ubuntu-latest
    steps:
    - run: exit 0

  aggregation:
    runs-on: ubuntu-latest
    needs:
      - workload-succeeding
      - workload-failing
    steps:
    - run: echo hi!
