on:
  push:

jobs:
  workload-succeeding:
    runs-on: ubuntu-latest
    steps:
    - run: exit 0

  workload-failing:
    runs-on: ubuntu-latest
    steps:
    - run: exit 1

  aggregation:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - workload-succeeding
      - workload-failing
    steps:
    - run: echo hi!
