name: Workload
run-name: "Workload (${{ github.ref_name }})"

on:
  workflow_dispatch:
    inputs:
      sha:
        type: string

jobs:
  workload:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
